const DB_NAME='tfp-ledger'; const DB_VERSION=1; const STORE='records';
const SETTINGS_KEY='tfp-ledger-settings'; const CATEGORIES_KEY='tfp-ledger-expense-categories';
const DEFAULT_CATEGORIES=['Fees','Advertising','Office Supplies','Software','Professional Services','Rent','Utilities','Insurance','Travel','Other'];
let db, records=[], editingId=null;
const $=id=>document.getElementById(id);
const money=n=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
const dateFmt=s=>s?new Date(s+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'';
const uid=()=>crypto.randomUUID();

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>{db=r.result;resolve()};r.onerror=()=>reject(r.error)})}
function getAll(){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function putMany(items){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);items.forEach(x=>s.put(x));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function clearDB(){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).clear();r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}

function loadSettings(){let s={};try{s=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}catch{};$('ghOwner').value=s.owner||'';$('ghRepo').value=s.repo||'';$('ghPath').value=s.path||'ledger.enc';$('rememberToken').checked=!!s.rememberToken;$('rememberPassword').checked=!!s.rememberPassword;if(s.rememberToken)$('ghToken').value=s.token||'';if(s.rememberPassword)$('encPassword').value=s.password||''}
function saveSettings(){const s={owner:$('ghOwner').value.trim(),repo:$('ghRepo').value.trim(),path:$('ghPath').value.trim()||'ledger.enc',rememberToken:$('rememberToken').checked,rememberPassword:$('rememberPassword').checked};if(s.rememberToken)s.token=$('ghToken').value;if(s.rememberPassword)s.password=$('encPassword').value;localStorage.setItem(SETTINGS_KEY,JSON.stringify(s));if(!s.rememberToken)$('ghToken').value='';if(!s.rememberPassword)$('encPassword').value=''}
function loadCategories(){try{const saved=JSON.parse(localStorage.getItem(CATEGORIES_KEY)||'null');if(Array.isArray(saved)&&saved.length)return [...new Set(saved.filter(Boolean))]}catch{};localStorage.setItem(CATEGORIES_KEY,JSON.stringify(DEFAULT_CATEGORIES));return [...DEFAULT_CATEGORIES]}
let categories=loadCategories();
function saveCategories(){categories=[...new Set(categories.map(x=>x.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));localStorage.setItem(CATEGORIES_KEY,JSON.stringify(categories));renderCategories()}
function renderCategories(){const el=$('categoryList');if(!el)return;el.innerHTML=categories.length?categories.map(c=>`<div class="category-item"><span>${esc(c)}</span><button type="button" class="delete-link" data-category-delete="${esc(c)}">Delete</button></div>`).join(''):'<div class="hint">No categories defined.</div>'}
function toast(msg){const t=$('toast');t.textContent=msg;t.style.display='block';clearTimeout(window._toast);window._toast=setTimeout(()=>t.style.display='none',2500)}

function refresh(){records.sort((a,b)=>(a.date||a.paymentDate||'').localeCompare(b.date||b.paymentDate||'')||String(a.createdAt||a.updatedAt||'').localeCompare(String(b.createdAt||b.updatedAt||'')));renderRegister();renderBilling();renderSummary();const visible=records.filter(r=>r.type!=='tombstone').length;$('recordCount').textContent=`${visible} record${visible===1?'':'s'}`;renderStatementPreview();renderCategories()}
function registerRows(){
 const income=records.filter(r=>r.type==='income'||r.type==='billing').map(r=>({date:r.type==='billing'?r.paymentDate:r.date,type:r.type==='billing'?'Billing payment':'Income',desc:r.description||'Income',income:Number(r.type==='billing'?r.receivedAmount:r.amount),expense:0,id:r.id}));
 const expenses=records.filter(r=>r.type==='expense').map(r=>({date:r.date,type:'Expense',desc:r.description||r.category||'Expense',income:0,expense:Number(r.amount),id:r.id}));
 return [...income,...expenses].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
}
function renderRegister(){let bal=0;const rows=registerRows();$('registerBody').innerHTML=rows.length?rows.map(r=>{bal+=r.income-r.expense;return `<tr><td>${dateFmt(r.date)}</td><td>${r.type}</td><td>${esc(r.desc)}</td><td class="num">${r.income?money(r.income):''}</td><td class="num">${r.expense?money(r.expense):''}</td><td class="num">${money(bal)}</td><td><button class="edit-link" data-edit="${r.id}">Edit</button> <button class="delete-link" data-delete="${r.id}">Delete</button></td></tr>`}).join(''):`<tr><td colspan="7">No transactions yet.</td></tr>`}
function renderBilling(){const b=records.filter(r=>r.type==='billing').sort((a,b)=>a.serviceDate.localeCompare(b.serviceDate));$('billingBody').innerHTML=b.length?b.map(r=>{const short=Math.max(0,Number(r.billedAmount)-Number(r.receivedAmount));return `<tr><td>${dateFmt(r.serviceDate)}</td><td>${dateFmt(r.paymentDate)}</td><td class="num">${money(r.billedAmount)}</td><td class="num">${money(r.receivedAmount)}</td><td class="num">${money(short)}</td><td><button class="edit-link" data-edit="${r.id}">Edit</button> <button class="delete-link" data-delete="${r.id}">Delete</button></td></tr>`}).join(''):`<tr><td colspan="6">No billing records yet.</td></tr>`}
function renderSummary(){const income=registerRows().reduce((a,r)=>a+r.income,0),exp=registerRows().reduce((a,r)=>a+r.expense,0),short=records.filter(r=>r.type==='billing').reduce((a,r)=>a+Math.max(0,Number(r.billedAmount)-Number(r.receivedAmount)),0);$('registerSummary').innerHTML=[['Income received',income],['Expenses',exp],['Net cash movement',income-exp],['Insurance shortfall',short]].map(([l,v])=>`<div class="summary"><div class="label">${l}</div><div class="value">${money(v)}</div></div>`).join('')}

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fieldsFor(kind,r={}){
 const expenseCategory=categories.includes(r.category)?r.category:'';
 const catOptions=categories.map(c=>`<option value="${esc(c)}" ${c===expenseCategory?'selected':''}>${esc(c)}</option>`).join('');
 if(kind==='income')return [['date','Date','date',r.date||today()],['amount','Amount received','number',r.amount??'','0.01'],['description','Description','text',r.description||'']];
 if(kind==='expense')return [['date','Date','date',r.date||today()],['amount','Amount','number',r.amount??'','0.01'],['category','Category','select',catOptions],['description','Description (optional)','text',r.description||'']];
 return [['serviceDate','Service date','date',r.serviceDate||today()],['paymentDate','Payment received','date',r.paymentDate||today()],['billedAmount','Amount billed','number',r.billedAmount??'','0.01'],['receivedAmount','Amount actually received','number',r.receivedAmount??'','0.01'],['description','Description (optional)','text',r.description||'']];
}
function openEntry(kind,id=null){
 editingId=id;const r=id?records.find(x=>x.id===id):{};if(id&&!r)return;
 const labels={income:id?'Edit Income':'New Income',expense:id?'Edit Expense':'New Expense',billing:id?'Edit Billing Payment':'New Billing Payment'};
 $('dialogTitle').textContent=labels[kind];
 $('entryFields').innerHTML=fieldsFor(kind,r).map(f=>f[2]==='select'?`<div class="field"><label>${f[1]}<select id="f_${f[0]}">${f[3]}</select></label></div>`:`<div class="field"><label>${f[1]}<input id="f_${f[0]}" type="${f[2]}" value="${esc(f[3])}" ${f[4]?'step="'+f[4]+'"':''}></label></div>`).join('');
 $('entryForm').dataset.kind=kind;$('entryDialog').showModal();
}
function today(){return new Date().toISOString().slice(0,10)}
$('cancelEntryBtn').onclick=()=>{$('entryDialog').close('cancel');editingId=null};
$('entryForm').addEventListener('submit',async e=>{e.preventDefault();if(e.submitter&&e.submitter.value==='cancel')return;const k=e.currentTarget.dataset.kind;let r=editingId?records.find(x=>x.id===editingId):{id:uid(),createdAt:Date.now(),type:k};if(!r)return;
 if(k==='income'){r.date=$('f_date').value;r.amount=Number($('f_amount').value);r.description=$('f_description').value.trim()||'Income'}
 if(k==='expense'){r.date=$('f_date').value;r.amount=Number($('f_amount').value);r.category=$('f_category').value;r.description=$('f_description').value.trim()||r.category||'Expense'}
 if(k==='billing'){r.serviceDate=$('f_serviceDate').value;r.paymentDate=$('f_paymentDate').value;r.billedAmount=Number($('f_billedAmount').value);r.receivedAmount=Number($('f_receivedAmount').value);r.description=$('f_description').value.trim()||'Insurance payment'}
 r.updatedAt=Date.now();if(!validate(r))return;await putMany([r]);records=await getAll();$('entryDialog').close('saved');editingId=null;refresh();setSyncDirty();});
function validate(r){if(!r.date&&r.type==='income' || !r.date&&r.type==='expense'){alert('Choose a date.');return false}if(r.type==='expense'&&!r.category){alert('Choose an expense category.');return false}if(r.type==='billing'&&(r.billedAmount<0||r.receivedAmount<0||r.receivedAmount>r.billedAmount)){alert('Received amount must be between $0 and the amount billed.');return false}if((r.amount??0)<0){alert('Amounts cannot be negative.');return false}return true}
document.addEventListener('click',async e=>{
 const edit=e.target.closest('[data-edit]');if(edit){const r=records.find(x=>x.id===edit.dataset.edit);if(r)openEntry(r.type,r.id);return}
 const delBtn=e.target.closest('[data-delete]');if(delBtn){if(confirm('Delete this record?')){const old=records.find(x=>x.id===delBtn.dataset.delete);if(old){await putMany([{id:old.id,type:'tombstone',deletedAt:Date.now(),updatedAt:Date.now()}])}records=await getAll();refresh();setSyncDirty()};return}
 const catDel=e.target.closest('[data-category-delete]');if(catDel){const c=catDel.dataset.categoryDelete;if(confirm(`Delete the category “${c}”? Existing expenses will keep their category.`)){categories=categories.filter(x=>x!==c);saveCategories()}}
});
$('addCategoryBtn').onclick=()=>{const input=$('newCategory'),name=input.value.trim();if(!name)return;if(categories.some(c=>c.toLowerCase()===name.toLowerCase())){toast('That category already exists.');return}categories.push(name);saveCategories();input.value='';input.focus()};
$('newCategory').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('addCategoryBtn').click()}});

function filtered(from,to){return records.filter(r=>r.type!=='tombstone'&&(()=>{const d=r.type==='billing'?r.paymentDate:r.date;return d&&(!from||d>=from)&&(!to||d<=to)})())}
function statementData(from,to){const rs=filtered(from,to),billing=rs.filter(r=>r.type==='billing'),income=rs.filter(r=>r.type==='income'),expenses=rs.filter(r=>r.type==='expense');const received=income.reduce((a,r)=>a+Number(r.amount),0)+billing.reduce((a,r)=>a+Number(r.receivedAmount),0),exp=expenses.reduce((a,r)=>a+Number(r.amount),0),billed=billing.reduce((a,r)=>a+Number(r.billedAmount),0),short=billing.reduce((a,r)=>a+Math.max(0,Number(r.billedAmount)-Number(r.receivedAmount)),0);return {rs,billing,income,expenses,received,exp,billed,short,net:received-exp}}
function renderStatementPreview(){const from=$('statementFrom').value,to=$('statementThrough').value;if(!from&&!to){$('statementPreview').innerHTML='<div class="hint">Choose a date range to preview the statement.</div>';return}const d=statementData(from,to);$('statementPreview').innerHTML=`<h2>True Faith Psychiatry</h2><div>${dateFmt(from)} – ${dateFmt(to)}</div><table><tbody><tr><td>Insurance payments received</td><td class="num">${money(d.billing.reduce((a,r)=>a+Number(r.receivedAmount),0))}</td></tr><tr><td>Other income</td><td class="num">${money(d.income.reduce((a,r)=>a+Number(r.amount),0))}</td></tr><tr class="total"><td>Actual income received</td><td class="num">${money(d.received)}</td></tr><tr><td>Insurance billed</td><td class="num">${money(d.billed)}</td></tr><tr><td>Insurance shortfall</td><td class="num">${money(d.short)}</td></tr><tr><td>Expenses</td><td class="num">${money(d.exp)}</td></tr><tr class="total"><td>Net cash movement</td><td class="num">${money(d.net)}</td></tr></tbody></table>`}
$('statementFrom').addEventListener('change',renderStatementPreview);$('statementThrough').addEventListener('change',renderStatementPreview);

const enc=new TextEncoder(),dec=new TextDecoder();
async function deriveKey(password,salt){const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function b64(bytes){let s='';bytes=new Uint8Array(bytes);for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
function unb64(s){const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
async function encryptData(items,password){if(!password)throw Error('Enter an encryption password in Settings.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(password,salt),plain=enc.encode(JSON.stringify({version:1,updatedAt:new Date().toISOString(),records:items})),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain);return JSON.stringify({format:'TFP-LEDGER-ENC',version:1,kdf:'PBKDF2-SHA256',iterations:210000,cipher:'AES-256-GCM',salt:b64(salt),iv:b64(iv),data:b64(cipher)})}
async function decryptData(text,password){const o=JSON.parse(text);if(o.format!=='TFP-LEDGER-ENC')throw Error('Not a TFP Ledger encrypted file.');const key=await deriveKey(password,unb64(o.salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(o.iv)},key,unb64(o.data));return JSON.parse(dec.decode(plain)).records}
function githubSettings(){const owner=$('ghOwner').value.trim(),repo=$('ghRepo').value.trim(),path=$('ghPath').value.trim()||'ledger.enc',token=$('ghToken').value.trim();if(!owner||!repo||!token)throw Error('Complete the GitHub owner, repository, and token fields in Settings.');return {owner,repo,path,token}}
async function gh(method,url,body){const headers={'Accept':'application/vnd.github+json','Authorization':`Bearer ${githubSettings().token}`,'X-GitHub-Api-Version':'2022-11-28'};if(body)headers['Content-Type']='application/json';const r=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(`GitHub ${r.status}: ${await r.text()}`);return r.status===204?null:r.json()}
async function push(){saveSettings();const s=githubSettings(),pass=$('encPassword').value;if(!pass)throw Error('Enter the encryption password in Settings.');$('syncStatus').textContent='Checking GitHub…';const url=`https://api.github.com/repos/${encodeURIComponent(s.owner)}/${encodeURIComponent(s.repo)}/contents/${s.path}`;let existing=null,remote=[];try{existing=await gh('GET',url);const text=decodeURIComponent(escape(atob(existing.content.replace(/\n/g,''))));remote=await decryptData(text,pass)}catch(e){if(!String(e.message).includes('GitHub 404'))throw e}const merged=[...mergeRecords(records,remote).values()];records=merged;await clearDB();await putMany(records);$('syncStatus').textContent='Encrypting…';const content=await encryptData(merged,pass);const body={message:`Update TFP Ledger ${new Date().toISOString()}`,content:btoa(unescape(encodeURIComponent(content))),branch:'main'};if(existing?.sha)body.sha=existing.sha;await gh('PUT',url,body);$('syncStatus').textContent='Synced';localStorage.setItem('tfp-last-sync',new Date().toISOString());toast('Ledger pushed to GitHub.')}
function mergeRecords(local,remote){const map=new Map();[...local,...remote].forEach(x=>{const old=map.get(x.id);if(!old||Number(x.updatedAt||x.createdAt||0)>=Number(old.updatedAt||old.createdAt||0))map.set(x.id,x)});return map}
async function pull(){saveSettings();const s=githubSettings(),pass=$('encPassword').value;if(!pass)throw Error('Enter the encryption password in Settings.');$('syncStatus').textContent='Pulling…';const url=`https://api.github.com/repos/${encodeURIComponent(s.owner)}/${encodeURIComponent(s.repo)}/contents/${s.path}`;const r=await gh('GET',url);const text=decodeURIComponent(escape(atob(r.content.replace(/\n/g,''))));const remote=await decryptData(text,pass);const map=mergeRecords(records,remote);records=[...map.values()];await clearDB();await putMany(records);refresh();$('syncStatus').textContent='Pulled + merged';toast(`Pulled ${remote.length} records and merged locally.`)}
function setSyncDirty(){$('syncStatus').textContent='Unsynced local changes'}
async function downloadText(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('exportBtn').onclick=async()=>{try{saveSettings();const p=$('encPassword').value;if(!p)throw Error('Enter an encryption password in Settings.');await downloadText(`tfp-ledger-${today()}.enc`,await encryptData(records,p),'application/json');toast('Encrypted backup exported.')}catch(e){alert(e.message)}};
$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const p=$('encPassword').value;if(!p)throw Error('Enter the encryption password in Settings.');const r=await decryptData(await f.text(),p);const map=mergeRecords(records,r);records=[...map.values()];await clearDB();await putMany(records);refresh();setSyncDirty();toast('Backup imported and merged.')}catch(err){alert('Could not import backup: '+err.message)}e.target.value=''};
$('clearBtn').onclick=async()=>{if(confirm('Clear all local ledger data? This does not delete the GitHub copy.')){await clearDB();records=[];refresh();setSyncDirty();toast('Local ledger cleared.')}};
$('pushBtn').onclick=async()=>{try{await push()}catch(e){$('syncStatus').textContent='Sync error';alert(e.message)}};$('pullBtn').onclick=async()=>{try{await pull()}catch(e){$('syncStatus').textContent='Sync error';alert(e.message)}};
['ghOwner','ghRepo','ghPath','ghToken','encPassword','rememberToken','rememberPassword'].forEach(id=>$(id).addEventListener('change',saveSettings));
$('addIncomeBtn').onclick=()=>openEntry('income');$('addExpenseBtn').onclick=()=>openEntry('expense');$('addBillingBtn').onclick=()=>openEntry('billing');$('newBillingBtn').onclick=()=>openEntry('billing');
$('statementBtn').onclick=()=>{const f=$('statementFrom').value,t=$('statementThrough').value;if(!f||!t||f>t){alert('Choose a valid date range first.');return}generatePDF(f,t)};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view+'View').classList.add('active')});

function pdfEsc(s){return String(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'?')}
function generatePDF(from,to){const d=statementData(from,to),lines=[];const add=(s,size=10)=>lines.push({s,size});add('True Faith Psychiatry',18);add(`Financial Statement: ${dateFmt(from)} - ${dateFmt(to)}`,11);add('');add(`Insurance payments received: ${money(d.billing.reduce((a,r)=>a+Number(r.receivedAmount),0))}`);add(`Other income received: ${money(d.income.reduce((a,r)=>a+Number(r.amount),0))}`);add(`Actual income received: ${money(d.received)}`,12);add('');add(`Insurance amount billed: ${money(d.billed)}`);add(`Insurance shortfall: ${money(d.short)}`);add('');add(`Expenses: ${money(d.exp)}`);add(`Net cash movement: ${money(d.net)}`,12);add('');add('Transactions');d.rs.sort((a,b)=>(a.type==='expense'?a.date:(a.paymentDate||a.date)).localeCompare(b.type==='expense'?b.date:(b.paymentDate||b.date))).slice(0,28).forEach(r=>{const date=r.type==='billing'?r.paymentDate:r.date;const desc=r.type==='billing'?`Insurance payment (${money(r.receivedAmount)})`:r.type==='expense'?`Expense: ${r.category||r.description}`:r.description||'Income';add(`${dateFmt(date)}  ${desc.slice(0,62)}`)});let content='BT\n',y=760;lines.forEach(l=>{content+=`/F1 ${l.size} Tf\n1 0 0 1 50 ${y} Tm\n(${pdfEsc(l.s)}) Tj\n`;y-=l.size+7});content+='ET';const objs=[];objs.push('<< /Type /Catalog /Pages 2 0 R >>');objs.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');objs.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>');objs.push(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);objs.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');let pdf='%PDF-1.4\n',offsets=[0];objs.forEach((o,i)=>{offsets[i+1]=pdf.length;pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const x=pdf.length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;downloadText(`tfp-statement-${from}-to-${to}.pdf`,pdf,'application/pdf')}

(async()=>{await openDB();loadSettings();records=await getAll();refresh();renderCategories();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});const d=new Date();const first=new Date(d.getFullYear(),d.getMonth(),1);$('statementFrom').value=first.toISOString().slice(0,10);$('statementThrough').value=today();renderStatementPreview();})();
